# A3Mailer Production Configuration
# AI-Powered Web3-Native Mail Server Configuration

[server]
hostname = "mail.example.com"
max_connections = 10000
worker_threads = 8
bind = ["0.0.0.0:25", "0.0.0.0:587", "0.0.0.0:143", "0.0.0.0:993", "0.0.0.0:8080"]

[logging]
level = "info"
output = "/var/log/a3mailer/a3mailer.log"
rotation = "daily"
max_files = 30

# AI Configuration
[ai]
enabled = true
model_path = "/opt/a3mailer/models"

[ai.threat_detection]
enabled = true
model_file = "threat-detection-v2.onnx"
confidence_threshold = 0.85
update_interval = "1h"
real_time_scanning = true

[ai.content_analysis]
enabled = true
nlp_model = "bert-base-multilingual"
sentiment_analysis = true
language_detection = true
content_classification = true

[ai.behavioral_analysis]
enabled = true
learning_rate = 0.001
anomaly_threshold = 0.95
training_interval = "24h"
user_profiling = true

[ai.predictive_analytics]
enabled = true
email_routing_optimization = true
delivery_time_prediction = true
spam_trend_analysis = true

# Web3 Configuration
[web3]
enabled = true

[web3.blockchain]
network = "ethereum"
rpc_url = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
contract_address = "0x742d35Cc6634C0532925a3b8D4C9db96c4b4d8b6"
gas_limit = 100000
gas_price = "20000000000"  # 20 gwei

[web3.identity]
enabled = true
did_method = "did:ethr"
resolver_url = "https://uniresolver.io"
verification_required = false

[web3.smart_contracts]
enabled = true
compliance_contract = "0x..."
governance_contract = "0x..."
access_control_contract = "0x..."

[web3.storage]
ipfs_enabled = true
ipfs_api = "https://ipfs.infura.io:5001"
ipfs_gateway = "https://ipfs.io"
pinning_service = "pinata"
pinata_api_key = "YOUR_PINATA_API_KEY"

# Storage Configuration
[storage]
type = "postgresql"
connection_string = "postgresql://a3mailer:password@postgres:5432/a3mailer"
max_connections = 100
connection_timeout = "30s"

[storage.cache]
type = "redis"
connection_string = "redis://:password@redis:6379/0"
ttl = "1h"
max_memory = "512MB"

[storage.search]
type = "elasticsearch"
connection_string = "http://elasticsearch:9200"
index_prefix = "a3mailer"

# Security Configuration
[security]
encryption_algorithm = "aes256"
key_derivation = "pbkdf2"
iterations = 100000

[security.tls]
cert_file = "/etc/ssl/certs/a3mailer.crt"
key_file = "/etc/ssl/private/a3mailer.key"
protocols = ["TLSv1.2", "TLSv1.3"]
ciphers = ["ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-RSA-AES128-GCM-SHA256"]

[security.authentication]
methods = ["password", "oauth2", "did"]
password_policy = "strong"
session_timeout = "24h"
max_login_attempts = 5

[security.spam_filter]
enabled = true
ai_powered = true
bayes_filter = true
dnsbl_checks = true
reputation_scoring = true

# SMTP Configuration
[smtp]
hostname = "mail.example.com"
banner = "A3Mailer ESMTP Server"
max_message_size = "50MB"
max_recipients = 100

[smtp.relay]
enabled = true
smart_host = "smtp.example.com"
authentication = true
username = "relay_user"
password = "relay_password"

# IMAP Configuration
[imap]
hostname = "mail.example.com"
max_connections_per_user = 10
idle_timeout = "30m"
search_cache_size = "100MB"

# POP3 Configuration
[pop3]
enabled = true
hostname = "mail.example.com"
max_connections_per_user = 3
session_timeout = "10m"

# JMAP Configuration
[jmap]
enabled = true
hostname = "mail.example.com"
max_concurrent_requests = 4
max_size_request = "10MB"
max_size_upload = "50MB"

# CalDAV/CardDAV Configuration
[caldav]
enabled = true
hostname = "mail.example.com"
max_resource_size = "1MB"

[carddav]
enabled = true
hostname = "mail.example.com"
max_resource_size = "1MB"

# WebDAV Configuration
[webdav]
enabled = true
hostname = "mail.example.com"
max_file_size = "100MB"

# Monitoring Configuration
[monitoring]
enabled = true
metrics_endpoint = "/metrics"
health_endpoint = "/health"

[monitoring.prometheus]
enabled = true
port = 9090
scrape_interval = "15s"

[monitoring.grafana]
enabled = true
port = 3000
admin_password = "admin"

# Backup Configuration
[backup]
enabled = true
schedule = "0 2 * * *"  # Daily at 2 AM
retention_days = 30
compression = "gzip"
encryption = true

[backup.destinations]
local_path = "/var/backups/a3mailer"
s3_bucket = "a3mailer-backups"
s3_region = "us-east-1"

# Clustering Configuration
[cluster]
enabled = false
node_id = "node-1"
discovery_method = "static"
nodes = ["node-1:8080", "node-2:8080", "node-3:8080"]

# Rate Limiting
[rate_limiting]
enabled = true
requests_per_minute = 60
burst_size = 10
whitelist = ["127.0.0.1", "::1"]

# Compliance Configuration
[compliance]
enabled = true
gdpr_enabled = true
hipaa_enabled = false
ccpa_enabled = true
audit_logging = true
data_retention_days = 2555  # 7 years

# Enterprise Features
[enterprise]
license_key = "YOUR_ENTERPRISE_LICENSE_KEY"
support_enabled = true
advanced_analytics = true
custom_branding = true
